# Backend Secret
# 주의: 이 파일은 Git에 커밋하지 마세요!
# 실제 배포 시 아래 명령어로 생성하세요:
# kubectl create secret generic backend-secret \
#   --from-literal=db-username=실제사용자명 \
#   --from-literal=db-password=실제비밀번호 \
#   -n backend

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  # 아래 값들을 실제 base64 인코딩된 값으로 변경하세요
  db-username: YWRtaW4=  # 'admin'의 base64
  db-password: cGFzc3dvcmQ=  # 'password'의 base64