# ML-Backend Secret
# 주의: 이 파일은 Git에 커밋하지 마세요!
# 실제 배포 시 아래 명령어로 생성하세요:
# kubectl create secret generic ml-backend-secret \
#   --from-literal=db-username=실제사용자명 \
#   --from-literal=db-password=실제비밀번호 \
#   -n ml-backend

#apiVersion: v1
#kind: Secret
#metadata:
#  name: ml-backend-secret
#  namespace: ml-backend
#type: Opaque
#data:
#  # 아래 값들을 실제 base64 인코딩된 값으로 변경하세요
#  # echo -n '실제값' | base64
#  db-username: YWRtaW4=  # 'admin'의 base64
#  db-password: cGFzc3dvcmQ=  # 'password'의 base64

# ML-Backend Secret - 민감한 정보들
apiVersion: v1
kind: Secret
metadata:
  name: ml-backend-secret
  namespace: ml-backend
type: Opaque
data:
  # OpenAI API Key (민감한 정보)
  OPENAI_API_KEY: c2stcHJvai12Y2hNWGxURWxraEtyZmJQbkhIQ3Nmanpz  # base64 인코딩된 값
  
  # 데이터베이스 비밀번호 (민감한 정보)
  DB_PASSWORD: YXBwX3VzZXJfcGFzc3dvcmQ=  # 'app_user_password'의 base64