apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    name: node-exporter
spec:
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
  selector:
    name: node-exporter