# ML-Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-backend
  namespace: ml-backend  # ml-backend 네임스페이스
  labels:
    app: ml-backend
    version: v1
spec:
  # 파드 복제본 수
  replicas: 1
  
  # 파드 선택자
  selector:
    matchLabels:
      app: ml-backend
      
  # Rolling Update 전략
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
  # 파드 템플릿
  template:
    metadata:
      labels:
        app: ml-backend
        version: v1
    spec:
      containers:
      - name: ml-backend
        # Docker Hub 이미지 (실제 이미지로 변경 필요)
        image: jaerimw/ml-chatbot:latest  # 현재 사용 중인 이미지
        imagePullPolicy: Always
        
        # 포트 설정
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
          
        # ConfigMap에서 환경변수 가져오기
        envFrom:
        - configMapRef:
            name: ml-backend-config
            
        # Secret에서 민감한 정보 가져오기
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ml-backend-secret
              key: db-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ml-backend-secret
              key: db-password
              
        # 리소스 제한
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
            
        # 헬스체크 (경로 확인 필요)
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
      # Private Docker Hub 사용 시 (필요한 경우)
      # imagePullSecrets:
      # - name: dockerhub-secret